feature: add `qux` interface
dmkonq/foo pull request #1
Opened 2023-11-13 09:49 UTC by dmkonq

This PR proposes addtion of interface for function `qux`.

2023-11-13 09:58 UTC, dmkonq reviewed
Seems good

2023-11-13 09:58 UTC, dmkonq commented on main.go
> +func qux() (string, error) {
Why qux? I'd rather use `asdf`.

2023-11-14 01:45 UTC, crowdigit requested changes
Function `"qux"` is supposed to return `"qux"` not `"foo"`. Fix it please.

2023-11-14 01:58 UTC, crowdigit reviewed
Good

2023-11-14 01:58 UTC, crowdigit commented on main.go
>  	return "foo", nil
It should return `"qux"`.

2023-11-14 02:00 UTC, crowdigit approved these changes

2023-11-14 02:00 UTC, merged